GET http://localhost:8080/user
###
GET http://localhost:8080/user/input?login=sdadsasda&password=14&confirmPassword=14
###
GET http://localhost:8080/user/input?login=sd123456789012345678&password=14&confirmPassword=14
